let AUTH_KEY = "b9fd373fac9a223a9ba79b42dbe37f61"
let BASE_URL = "http://api.positionstack.com/v1/"

// query the forward api endpoint and specify the access key and query parameter which is an address
// naive assumption that the first response from the api is the correct one
// note: the api returns a list of potential matches
export default function geocode(address) {
  return fetch(`${BASE_URL}forward?access_key=${AUTH_KEY}&query=${address}`)
    .then(res => res.json())
    .then(data => {
      return data.data[0]["latitude"], data.data[0]["longitude"]
    })
}

//  Sample Response
// {
//     "data": [
//         {
//             "latitude": 28.523602,
//             "longitude": -80.681459,
//             "type": "venue",
//             "name": "Kennedy Space Center Visitor Complex",
//             "number": "9500",
//             "postal_code": "32953",
//             "street": "Space Commerce Way",
//             "confidence": 0.8,
//             "region": "Florida",
//             "region_code": "FL",
//             "county": "Brevard County",
//             "locality": "Merritt Island",
//             "administrative_area": null,
//             "neighbourhood": null,
//             "country": "United States",
//             "country_code": "USA",
//             "continent": "North America",
//             "label": "Kennedy Space Center Visitor Complex, Merritt Island, FL, USA"
//         },
//         {
//             "latitude": -37.919185,
//             "longitude": 145.078302,
//             "type": "address",
//             "name": "39A Kennedy Street",
//             "number": "39A",
//             "postal_code": "3165",
//             "street": "Kennedy Street",
//             "confidence": 1,
//             "region": "Victoria",
//             "region_code": "VIC",
//             "county": "Glen Eira",
//             "locality": "Bentleigh East",
//             "administrative_area": "Bentleigh East",
//             "neighbourhood": null,
//             "country": "Australia",
//             "country_code": "AUS",
//             "continent": "Oceania",
//             "label": "39A Kennedy Street, Bentleigh East, VIC, Australia"
//         },
//         {
//             "latitude": -36.765687,
//             "longitude": 174.742139,
//             "type": "address",
//             "name": "39A Kennedy Avenue",
//             "number": "39A",
//             "postal_code": null,
//             "street": "Kennedy Avenue",
//             "confidence": 1,
//             "region": "Auckland Region",
//             "region_code": "AU",
//             "county": "Auckland",
//             "locality": "Forrest Hill",
//             "administrative_area": "Auckland",
//             "neighbourhood": null,
//             "country": "New Zealand",
//             "country_code": "NZL",
//             "continent": "Oceania",
//             "label": "39A Kennedy Avenue, Forrest Hill, AU, New Zealand"
//         },
//         {
//             "latitude": 44.690823,
//             "longitude": -63.52808,
//             "type": "address",
//             "name": "39A Kennedy Dr",
//             "number": "39A",
//             "postal_code": "B2X 1N6",
//             "street": "Kennedy Dr",
//             "confidence": 1,
//             "region": "Nova Scotia",
//             "region_code": "NS",
//             "county": "Halifax",
//             "locality": null,
//             "administrative_area": null,
//             "neighbourhood": null,
//             "country": "Canada",
//             "country_code": "CAN",
//             "continent": "North America",
//             "label": "39A Kennedy Dr, NS, Canada"
//         },
//         {
//             "latitude": -27.967803,
//             "longitude": 24.762992,
//             "type": "address",
//             "name": "39A Kennedy Street",
//             "number": "39A",
//             "postal_code": null,
//             "street": "Kennedy Street",
//             "confidence": 1,
//             "region": "Northern Cape",
//             "region_code": "NC",
//             "county": "Frances Baard",
//             "locality": null,
//             "administrative_area": null,
//             "neighbourhood": null,
//             "country": "South Africa",
//             "country_code": "ZAF",
//             "continent": "Africa",
//             "label": "39A Kennedy Street, NC, South Africa"
//         },
//         {
//             "latitude": 42.100134,
//             "longitude": -71.030362,
//             "type": "address",
//             "name": "39A Kennedy Drive",
//             "number": "39A",
//             "postal_code": "02301",
//             "street": "Kennedy Drive",
//             "confidence": 1,
//             "region": "Massachusetts",
//             "region_code": "MA",
//             "county": "Plymouth County",
//             "locality": "Brockton",
//             "administrative_area": "Brockton",
//             "neighbourhood": null,
//             "country": "United States",
//             "country_code": "USA",
//             "continent": "North America",
//             "label": "39A Kennedy Drive, Brockton, MA, USA"
//         },
//         {
//             "latitude": 28.51536,
//             "longitude": -80.681882,
//             "type": "venue",
//             "name": "Kennedy Space Center Visitor Complex (Visitor Entrance)",
//             "number": "9500",
//             "postal_code": "32953",
//             "street": "Space Commerce Way",
//             "confidence": 0.8,
//             "region": "Florida",
//             "region_code": "FL",
//             "county": "Brevard County",
//             "locality": "Merritt Island",
//             "administrative_area": null,
//             "neighbourhood": null,
//             "country": "United States",
//             "country_code": "USA",
//             "continent": "North America",
//             "label": "Kennedy Space Center Visitor Complex (Visitor Entrance), Merritt Island, FL, USA"
//         },
//         {
//             "latitude": 51.880613,
//             "longitude": 5.705017,
//             "type": "address",
//             "name": "Kennedysingel 39a",
//             "number": "39a",
//             "postal_code": "6645AT",
//             "street": "Kennedysingel",
//             "confidence": 1,
//             "region": "Gelderland",
//             "region_code": "GE",
//             "county": null,
//             "locality": "Winssen",
//             "administrative_area": "Beuningen",
//             "neighbourhood": "Winssen-Centrum",
//             "country": "Netherlands",
//             "country_code": "NLD",
//             "continent": "Europe",
//             "label": "Kennedysingel 39a, Winssen, GE, Netherlands"
//         },
//         {
//             "latitude": 50.948395,
//             "longitude": 5.95923,
//             "type": "address",
//             "name": "Kennedylaan 39A",
//             "number": "39A",
//             "postal_code": "6441JB",
//             "street": "Kennedylaan",
//             "confidence": 1,
//             "region": "Limburg",
//             "region_code": "LB",
//             "county": null,
//             "locality": "Brunssum",
//             "administrative_area": null,
//             "neighbourhood": "De Streek",
//             "country": "Netherlands",
//             "country_code": "NLD",
//             "continent": "Europe",
//             "label": "Kennedylaan 39A, Brunssum, LB, Netherlands"
//         },
//         {
//             "latitude": 40.553771,
//             "longitude": 8.317828,
//             "type": "address",
//             "name": "Via Fratelli Kennedy 39A",
//             "number": "39A",
//             "postal_code": "07041",
//             "street": "Via Fratelli Kennedy",
//             "confidence": 1,
//             "region": "Sassari",
//             "region_code": "SS",
//             "county": null,
//             "locality": "Alghero",
//             "administrative_area": "Alghero",
//             "neighbourhood": null,
//             "country": "Italy",
//             "country_code": "ITA",
//             "continent": "Europe",
//             "label": "Via Fratelli Kennedy 39A, Alghero, SS, Italy"
//         }
//     ]
// }